exports.CONNECTED = 'WEBSOCKETS/CONNECTED';
exports.MEMORY_STAT_RECEIVED = 'WEBSOCKETS/MEMORY_STAT_RECEIVED';
exports.INVALID_MESSAGE_RECEIVED = 'WEBSOCKETS/INVALID_MESSAGE_RECEIVED';
exports.MEMORY_ALERT_CREATED = 'WEBSOCKETS/MEMORY_ALERT_CREATED';
exports.MEMORY_ALERT_UPDATED = 'WEBSOCKETS/MEMORY_ALERT_UPDATED';
